/*
Copyright 2023 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/maiqueb/persistentips/pkg/crd/persistentip/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIPAMLeases implements IPAMLeaseInterface
type FakeIPAMLeases struct {
	Fake *FakeK8sV1alpha1
	ns   string
}

var ipamleasesResource = v1alpha1.SchemeGroupVersion.WithResource("ipamleases")

var ipamleasesKind = v1alpha1.SchemeGroupVersion.WithKind("IPAMLease")

// Get takes name of the iPAMLease, and returns the corresponding iPAMLease object, and an error if there is any.
func (c *FakeIPAMLeases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IPAMLease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ipamleasesResource, c.ns, name), &v1alpha1.IPAMLease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMLease), err
}

// List takes label and field selectors, and returns the list of IPAMLeases that match those selectors.
func (c *FakeIPAMLeases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IPAMLeaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ipamleasesResource, ipamleasesKind, c.ns, opts), &v1alpha1.IPAMLeaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IPAMLeaseList{ListMeta: obj.(*v1alpha1.IPAMLeaseList).ListMeta}
	for _, item := range obj.(*v1alpha1.IPAMLeaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iPAMLeases.
func (c *FakeIPAMLeases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ipamleasesResource, c.ns, opts))

}

// Create takes the representation of a iPAMLease and creates it.  Returns the server's representation of the iPAMLease, and an error, if there is any.
func (c *FakeIPAMLeases) Create(ctx context.Context, iPAMLease *v1alpha1.IPAMLease, opts v1.CreateOptions) (result *v1alpha1.IPAMLease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ipamleasesResource, c.ns, iPAMLease), &v1alpha1.IPAMLease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMLease), err
}

// Update takes the representation of a iPAMLease and updates it. Returns the server's representation of the iPAMLease, and an error, if there is any.
func (c *FakeIPAMLeases) Update(ctx context.Context, iPAMLease *v1alpha1.IPAMLease, opts v1.UpdateOptions) (result *v1alpha1.IPAMLease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ipamleasesResource, c.ns, iPAMLease), &v1alpha1.IPAMLease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMLease), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIPAMLeases) UpdateStatus(ctx context.Context, iPAMLease *v1alpha1.IPAMLease, opts v1.UpdateOptions) (*v1alpha1.IPAMLease, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ipamleasesResource, "status", c.ns, iPAMLease), &v1alpha1.IPAMLease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMLease), err
}

// Delete takes name of the iPAMLease and deletes it. Returns an error if one occurs.
func (c *FakeIPAMLeases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ipamleasesResource, c.ns, name, opts), &v1alpha1.IPAMLease{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIPAMLeases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ipamleasesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IPAMLeaseList{})
	return err
}

// Patch applies the patch and returns the patched iPAMLease.
func (c *FakeIPAMLeases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IPAMLease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipamleasesResource, c.ns, name, pt, data, subresources...), &v1alpha1.IPAMLease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMLease), err
}
