name: Release the library
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release library
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Release the library
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            artifacts/k8s.cni.cncf.io_ipamleases.yaml